### ISSUE TITLE
Add a way to have the `CORE_D_DOTFILE` not stored in `$HOME`/`$USERPROFILE`

### ISSUE THREAD

**Issue by BurnerWah** [mantoni/core_d.js#13]
The core_d dotfiles are hard-coded to be stored in the user's HOME folder, which seems like an oversight. (https://github.com/mantoni/core_d.js/blob/master/lib/portfile.js#L6-L7)

I would usually expect such files to be either in `$XDG_RUNTIME_HOME` or `$XDG_CACHE_HOME`, but it'd probably be easier to just add a user-controlled variable like `CORE_D_HOME` which is used if it's set.

**Comment by mantoni** [comment]
Hey, thank you for bringing this up. This is as old as `eslint_d` when I started it as a quick hack. I agree that `XDG` should be respected.

Since the file is created and removed by `core_d`, I would place an `XDG` check here. The whole idea of this project is to handle all the "service" related management work.

Would you like to send a PR?

Also requested in mantoni/eslint_d.js#158
